version: '3.8'

services:
  db:
    image: postgres:16
    container_name: red_soft_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: red_soft_web
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app/
    command: ./run_server.sh
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./staticfiles/.:/code/public/staticfiles
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web

volumes:
  postgres_data: